const canvas = document.querySelector('#network-canvas');
const ctx = canvas.getContext('2d');
let points = [];
const pointer = { x: 0, y: 0 };
function resize() { canvas.width = innerWidth * devicePixelRatio; canvas.height = innerHeight * devicePixelRatio; ctx.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0); points = Array.from({ length: innerWidth < 800 ? 38 : 82 }, () => ({ x: Math.random() * innerWidth, y: Math.random() * innerHeight, vx: (Math.random() - .5) * .16, vy: (Math.random() - .5) * .16, r: Math.random() * 1.7 + .3 })); }
function draw() { ctx.clearRect(0, 0, innerWidth, innerHeight); points.forEach((p, i) => { p.x += p.vx; p.y += p.vy; if (p.x < 0 || p.x > innerWidth) p.vx *= -1; if (p.y < 0 || p.y > innerHeight) p.vy *= -1; const dx = p.x - pointer.x; const dy = p.y - pointer.y; const distance = Math.sqrt(dx * dx + dy * dy); if (distance < 170) { ctx.strokeStyle = `rgba(104,216,220,${(1 - distance / 170) * .22})`; ctx.beginPath(); ctx.moveTo(p.x, p.y); ctx.lineTo(pointer.x, pointer.y); ctx.stroke(); } for (let j = i + 1; j < points.length; j++) { const q = points[j]; const d = Math.hypot(p.x - q.x, p.y - q.y); if (d < 105) { ctx.strokeStyle = `rgba(204,250,103,${(1 - d / 105) * .12})`; ctx.beginPath(); ctx.moveTo(p.x, p.y); ctx.lineTo(q.x, q.y); ctx.stroke(); } } ctx.fillStyle = i % 9 === 0 ? '#ccfa67' : '#68d8dc'; ctx.globalAlpha = i % 9 === 0 ? .8 : .35; ctx.beginPath(); ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2); ctx.fill(); ctx.globalAlpha = 1; }); requestAnimationFrame(draw); }
addEventListener('resize', resize); addEventListener('pointermove', (e) => { pointer.x = e.clientX; pointer.y = e.clientY; document.querySelector('.cursor').style.left = `${e.clientX}px`; document.querySelector('.cursor').style.top = `${e.clientY}px`; document.querySelector('.cursor-ring').style.left = `${e.clientX}px`; document.querySelector('.cursor-ring').style.top = `${e.clientY}px`; });
resize(); draw();
const menu = document.querySelector('.menu-button'); const drawer = document.querySelector('.nav-drawer'); menu.addEventListener('click', () => { const open = drawer.classList.toggle('open'); menu.setAttribute('aria-expanded', open); }); document.querySelectorAll('.nav-drawer a').forEach((link) => link.addEventListener('click', () => { drawer.classList.remove('open'); menu.setAttribute('aria-expanded', 'false'); }));
function tick() { document.querySelector('#clock').textContent = new Date().toLocaleTimeString('en-GB'); } tick(); setInterval(tick, 1000);
document.querySelectorAll('a, button').forEach((item) => { item.addEventListener('mouseenter', () => document.querySelector('.cursor-ring').style.transform = 'translate(-50%,-50%) scale(1.7)'); item.addEventListener('mouseleave', () => document.querySelector('.cursor-ring').style.transform = 'translate(-50%,-50%) scale(1)'); });